#!/usr/bin/env python3
"""Generate Supabase SQL data inserts for STAUFF catalogue page 44."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK_PATH = ROOT / "data" / "!STAUFF_page44_ordering_codes(Ordering Codes).xlsx"
OUTPUT_PATH = ROOT / "db" / "page44_weld_plate_data.sql"

TABLE_NAME = 'stauff_clamps."Weld Plate for Single Clamps (SPAL) and Double Clamps (SPAS)"'
OVERVIEW_TABLE = 'stauff_clamps."Catalogue Overview"'
PRODUCTS = "Weld Plate for Single Clamps (SPAL) and Double Clamps (SPAS)"

TARGET_COLUMNS = [
    "catalogue_page_title",
    "catalogue_name",
    "permutation_summary",
    "ordering_code",
    "product_type",
    "product_description",
    "stauff_group",
    "din_group",
    "thread_code",
    "thread",
    "material_code",
    "material",
    "l1_mm",
    "l2_mm",
    "b_b1_mm",
    "b2_mm",
    "d1_mm",
]

NUMERIC_COLUMNS = {"l1_mm", "l2_mm", "b_b1_mm", "b2_mm", "d1_mm"}


def to_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def text_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def numeric_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    return str(value)


def sql_literal(column: str, value: Any) -> str:
    if column in NUMERIC_COLUMNS:
        return numeric_literal(value)
    return text_literal(to_text(value))


def row_has_data(row: tuple[Any, ...]) -> bool:
    return any(to_text(value) is not None for value in row)


def load_rows() -> list[dict[str, Any]]:
    wb = openpyxl.load_workbook(WORKBOOK_PATH, data_only=True, read_only=True)
    ws = wb["in"]

    catalogue_page_title = to_text(ws.cell(row=1, column=1).value)
    catalogue_name = to_text(ws.cell(row=2, column=1).value)
    permutation_summary = to_text(ws.cell(row=3, column=1).value)

    rows: list[dict[str, Any]] = []
    for row in ws.iter_rows(min_row=6, max_row=ws.max_row, values_only=True):
        if not row_has_data(row):
            continue

        rows.append(
            {
                "catalogue_page_title": catalogue_page_title,
                "catalogue_name": catalogue_name,
                "permutation_summary": permutation_summary,
                "ordering_code": row[0],
                "product_type": row[1],
                "product_description": row[2],
                "stauff_group": row[3],
                "din_group": row[4],
                "thread_code": row[5],
                "thread": row[6],
                "material_code": row[7],
                "material": row[8],
                "l1_mm": row[9],
                "l2_mm": row[10],
                "b_b1_mm": row[11],
                "b2_mm": row[12],
                "d1_mm": row[13],
            }
        )

    return rows


def validate_rows(rows: list[dict[str, Any]]) -> None:
    if len(rows) != 200:
        raise SystemExit(f"Expected 200 rows, found {len(rows)}")

    ordering_codes = [row["ordering_code"] for row in rows]
    if len(ordering_codes) != len(set(ordering_codes)):
        raise SystemExit("Duplicate ordering codes detected")

    counts: dict[str, int] = {}
    for row in rows:
        product_type = str(row["product_type"])
        counts[product_type] = counts.get(product_type, 0) + 1

    if counts != {"SPAL": 100, "SPAS": 100}:
        raise SystemExit(f"Unexpected product type counts: {counts}")


def render_insert(rows: list[dict[str, Any]]) -> str:
    column_sql = ", ".join(TARGET_COLUMNS)
    values_sql = []

    for row in rows:
        values = ", ".join(sql_literal(column, row[column]) for column in TARGET_COLUMNS)
        values_sql.append(f"  ({values})")

    return (
        f"insert into {TABLE_NAME} ({column_sql}) values\n"
        + ",\n".join(values_sql)
        + ";\n"
    )


def render_overview_insert() -> str:
    overview_catalogue_name = "Heavy Series (DIN 3015, Part 2) - " + PRODUCTS
    return f"""delete from {OVERVIEW_TABLE}
where products = {text_literal(PRODUCTS)}
  and product_type in ('SPAL', 'SPAS');

insert into {OVERVIEW_TABLE} (catalogue_name, products, product_type, permutations) values
  ({text_literal(overview_catalogue_name)}, {text_literal(PRODUCTS)}, 'SPAL', '100'),
  ({text_literal(overview_catalogue_name)}, {text_literal(PRODUCTS)}, 'SPAS', '100');
"""


def render_sql(rows: list[dict[str, Any]]) -> str:
    return (
        "-- Generated by scripts/generate_page44_weld_plate_sql.py\n"
        "-- Run after db/page44_weld_plate_schema.sql.\n"
        "begin;\n"
        f"truncate table {TABLE_NAME} restart identity;\n\n"
        + render_insert(rows)
        + "\n"
        + render_overview_insert()
        + "\ncommit;\n"
    )


def main() -> None:
    rows = load_rows()
    validate_rows(rows)
    OUTPUT_PATH.write_text(render_sql(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print("Rows: 200")
    print("Product types: SPAL=100, SPAS=100")


if __name__ == "__main__":
    main()
